site_name: Technical Notes
theme:
  name: 'material'
nav:
  - Home: index.md
  - Computer:
      - Linux:
        - "computer/linux/ubuntu.md"
      - PopularApps:
        - "computer/popularapps/mkdocs.md"
  - Computer Languages:
      - C++:
        - "languages/cplusplus/cplusplus.md"
      - Cuda:
        - "languages/cuda/cuda.md"
      - Python:
        - "languages/python/python.md"
  - Machine Learning:
      - TensorFlow:
        - "machine_learning/tensorflow/tensorflow.md"
      - MLops:
        - "machine_learning/mlops/hydra.md"
